// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh_zU8cm-7eP2bfZDEAqeocI3qxdsD3i4',
    appId: '1:684725372087:web:d31642924e33d209eb3932',
    messagingSenderId: '684725372087',
    projectId: 'flutter-chat-app-2da0e',
    authDomain: 'flutter-chat-app-2da0e.firebaseapp.com',
    storageBucket: 'flutter-chat-app-2da0e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8QyAeb_gIq36YFMi3YjB31_pzWFWy0Sg',
    appId: '1:684725372087:android:b9f0db7c23831e34eb3932',
    messagingSenderId: '684725372087',
    projectId: 'flutter-chat-app-2da0e',
    storageBucket: 'flutter-chat-app-2da0e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMxdv2zy3zq8dJ6QJnCUedX3TZkKYtMyY',
    appId: '1:684725372087:ios:88966a662210c145eb3932',
    messagingSenderId: '684725372087',
    projectId: 'flutter-chat-app-2da0e',
    storageBucket: 'flutter-chat-app-2da0e.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMxdv2zy3zq8dJ6QJnCUedX3TZkKYtMyY',
    appId: '1:684725372087:ios:88966a662210c145eb3932',
    messagingSenderId: '684725372087',
    projectId: 'flutter-chat-app-2da0e',
    storageBucket: 'flutter-chat-app-2da0e.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAh_zU8cm-7eP2bfZDEAqeocI3qxdsD3i4',
    appId: '1:684725372087:web:fd3f899b4c0e6034eb3932',
    messagingSenderId: '684725372087',
    projectId: 'flutter-chat-app-2da0e',
    authDomain: 'flutter-chat-app-2da0e.firebaseapp.com',
    storageBucket: 'flutter-chat-app-2da0e.firebasestorage.app',
  );

}